"""
Combinatorial-optimization problem definitions for the TDES *heuristic-evolution*
layer (the FunSearch / AlphaEvolve pattern: evolve the priority function, never
the solution).

The unit the LLM evolves is a single scalar **priority function**

    def priority(v, graph) -> float

that is plugged into a *fixed, deterministic greedy harness* owned by this
module. The harness — not the LLM — guarantees feasibility (it only ever emits a
valid independent set / a valid bipartition) and recomputes the objective
*exactly*. This mirrors FunSearch's bin-packing/cap-set design and is what makes
the result trustworthy: correctness comes from this code, the LLM only proposes
the ranking heuristic.

A ``graph`` handed to ``priority`` is a read-only :class:`GraphView` exposing
``n``, ``neighbors(v)``, ``degree(v)``, ``weight(u, v)`` and a small ``state``
dict the harness updates as it builds the solution — so a heuristic can look at
how many neighbors are still unassigned, etc. The same GraphView powers the
*baseline* classical heuristic, so the heuristic-vs-baseline comparison is
apples-to-apples (same harness, different priority).

Two problems are provided:

  * ``MaxCut``  — priority defines the greedy *processing order*; each vertex is
    then placed on the side that maximizes immediate cut weight. Objective:
    total weight of edges crossing the partition (maximize).
  * ``MIS``     — maximum independent set; greedy repeatedly takes the highest
    priority remaining vertex and removes it + its neighbors. Objective: set
    size (maximize). Vertex-cover is the trivial complement V \\ IS.

Instances are generated by *class* (``sparse`` / ``dense`` / ``clustered``) with
a fixed seed, so a portfolio candidate with one module per class has a natural
complementary-coverage structure for crossover to exploit.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Sequence, Tuple

# Instance classes shared by both problems. A portfolio candidate has one module
# (one specialized priority function) per class; a fixed dispatcher routes each
# instance to its class's module.
CLASSES: Tuple[str, ...] = ("sparse", "dense", "clustered")


# ---------------------------------------------------------------------------
# Instance representation (JSON-serializable so it crosses the subprocess line)
# ---------------------------------------------------------------------------


@dataclass
class Instance:
    """A single graph instance, tagged with its class."""

    id: str
    cls: str
    n: int
    edges: List[Tuple[int, int, float]]  # (u, v, weight); weight=1 for unweighted

    def to_json(self) -> dict:
        return {"id": self.id, "cls": self.cls, "n": self.n, "edges": [list(e) for e in self.edges]}

    @classmethod
    def from_json(cls, d: dict) -> "Instance":
        return cls(
            id=d["id"],
            cls=d["cls"],
            n=int(d["n"]),
            edges=[(int(u), int(v), float(w)) for u, v, w in d["edges"]],
        )


class GraphView:
    """Read-only adjacency view passed to an evolved ``priority(v, graph)``.

    Exposes only safe, cheap accessors plus a mutable ``state`` dict the harness
    fills in (e.g. which vertices are still available, current partial
    assignment). The heuristic may read ``state`` but should not rely on mutating
    it — the harness owns the construction loop.
    """

    __slots__ = ("n", "_adj", "_w", "state")

    def __init__(self, n: int, edges: Sequence[Tuple[int, int, float]]):
        self.n = n
        self._adj: List[set] = [set() for _ in range(n)]
        self._w: Dict[Tuple[int, int], float] = {}
        for u, v, w in edges:
            if u == v:
                continue
            self._adj[u].add(v)
            self._adj[v].add(u)
            self._w[(u, v)] = self._w[(v, u)] = float(w)
        self.state: Dict[str, object] = {}

    def neighbors(self, v: int) -> set:
        return self._adj[v]

    def degree(self, v: int) -> int:
        return len(self._adj[v])

    def weight(self, u: int, v: int) -> float:
        return self._w.get((u, v), 0.0)

    def adjacent(self, u: int, v: int) -> bool:
        return v in self._adj[u]


# ---------------------------------------------------------------------------
# Problem base + concrete problems
# ---------------------------------------------------------------------------

PriorityFn = Callable[[int, GraphView], float]


@dataclass
class HarnessResult:
    """Outcome of running one priority function on one instance."""

    feasible: bool
    quality: float
    solution: List[int]
    error: str = ""


class Problem:
    """Abstract problem: instance generation + fixed greedy harness + exact checks."""

    name: str = "abstract"
    sense: str = "max"  # objective sense (both problems here maximize)

    # -- instance generation --------------------------------------------------
    def generate(self, cls: str, n: int, seed: int) -> Instance:
        raise NotImplementedError

    def make_instances(self, cls: str, count: int, *, base_seed: int, n: int) -> List[Instance]:
        return [self.generate(cls, n, base_seed + i) for i in range(count)]

    # -- harness (fixed; feasibility guaranteed here) -------------------------
    def run(self, priority: PriorityFn, inst: Instance) -> HarnessResult:
        raise NotImplementedError

    # -- exact objective recomputation (never trusts the heuristic) -----------
    def objective(self, inst: Instance, solution: List[int]) -> float:
        raise NotImplementedError

    def verify(self, inst: Instance, solution: List[int]) -> Tuple[bool, str]:
        """Exact feasibility check. Returns (ok, reason)."""
        raise NotImplementedError

    # -- the classical baseline heuristic (runs through the same harness) -----
    @property
    def baseline_priority_source(self) -> str:
        raise NotImplementedError


class MaxCut(Problem):
    """Weighted Max-Cut via *evolved local-search move selection*.

    The harness runs a fixed-budget 1-flip local search starting from the
    all-zero partition. At each step it computes every vertex's *gain* (the cut
    increase from flipping it) and exposes the gains in ``graph.state["gain"]``
    and the current sides in ``graph.state["side"]``. The evolved
    ``priority(v, graph)`` is the **move selector**: it ranks the currently
    *improving* vertices (gain > 0) and the harness flips the highest-ranked one.
    A constant priority degrades to an arbitrary improving move (a weak local
    search); the classical strong rule is ``priority = graph.state['gain'][v]``
    (steepest ascent). Feasibility is automatic — every partition is valid.
    """

    name = "maxcut"

    def generate(self, cls: str, n: int, seed: int) -> Instance:
        rng = random.Random(seed)
        edges = _gen_graph(cls, n, rng, weighted=True)
        return Instance(id=f"{self.name}-{cls}-n{n}-s{seed}", cls=cls, n=n, edges=edges)

    def run(self, priority: PriorityFn, inst: Instance) -> HarnessResult:
        g = GraphView(inst.n, inst.edges)
        n = inst.n
        side: List[int] = [0] * n
        # gain[v] = cut change from flipping v. From the all-zero start every
        # vertex's gain equals its weighted degree.
        gain: List[float] = [0.0] * n
        for v in range(n):
            gain[v] = sum(g.weight(v, u) for u in g.neighbors(v))
        g.state["side"] = side
        g.state["gain"] = gain
        budget = max(1, n)
        for _ in range(budget):
            improving = [v for v in range(n) if gain[v] > 1e-12]
            if not improving:
                break
            try:
                v = max(improving, key=lambda x: priority(x, g))
            except Exception as e:  # noqa: BLE001 - surfaced as CEGIS feedback
                return HarnessResult(False, 0.0, [], f"priority() raised: {e!r}")
            a = side[v]
            for u in g.neighbors(v):
                gain[u] += -2.0 * g.weight(u, v) * (1.0 if side[u] == a else -1.0)
            gain[v] = -gain[v]
            side[v] = 1 - a
        ok, reason = self.verify(inst, side)
        if not ok:
            return HarnessResult(False, 0.0, side, reason)
        return HarnessResult(True, self.objective(inst, side), side)

    def objective(self, inst: Instance, solution: List[int]) -> float:
        cut = 0.0
        for u, v, w in inst.edges:
            if solution[u] != solution[v]:
                cut += w
        return cut

    def verify(self, inst: Instance, solution: List[int]) -> Tuple[bool, str]:
        if len(solution) != inst.n:
            return False, f"partition has {len(solution)} entries, expected {inst.n}"
        if any(s not in (0, 1) for s in solution):
            return False, "partition entries must all be 0 or 1"
        return True, ""

    @property
    def baseline_priority_source(self) -> str:
        # Classic steepest-ascent local search: always take the highest-gain flip.
        return (
            "def priority(v, graph):\n"
            "    # Baseline: steepest ascent (pick the largest-gain improving flip).\n"
            "    return graph.state['gain'][v]\n"
        )


class MIS(Problem):
    """Maximum Independent Set. Greedy: repeatedly take the highest-priority
    available vertex, add it to the set, and remove it and its neighbors."""

    name = "mis"

    def generate(self, cls: str, n: int, seed: int) -> Instance:
        rng = random.Random(seed)
        edges = _gen_graph(cls, n, rng, weighted=False)
        return Instance(id=f"{self.name}-{cls}-n{n}-s{seed}", cls=cls, n=n, edges=edges)

    def run(self, priority: PriorityFn, inst: Instance) -> HarnessResult:
        g = GraphView(inst.n, inst.edges)
        available = set(range(inst.n))
        g.state["available"] = available
        chosen: List[int] = []
        guard = 0
        while available and guard <= inst.n:
            guard += 1
            try:
                v = max(available, key=lambda x: priority(x, g))
            except Exception as e:  # noqa: BLE001
                return HarnessResult(False, 0.0, [], f"priority() raised: {e!r}")
            chosen.append(v)
            available.discard(v)
            available.difference_update(g.neighbors(v))
        ok, reason = self.verify(inst, chosen)
        if not ok:
            return HarnessResult(False, 0.0, chosen, reason)
        return HarnessResult(True, float(len(chosen)), sorted(chosen))

    def objective(self, inst: Instance, solution: List[int]) -> float:
        return float(len(solution))

    def verify(self, inst: Instance, solution: List[int]) -> Tuple[bool, str]:
        s = set(solution)
        if len(s) != len(solution):
            return False, "independent set contains duplicate vertices"
        for u, v, _ in inst.edges:
            if u in s and v in s:
                return False, f"vertices {u} and {v} are adjacent but both selected"
        return True, ""

    @property
    def baseline_priority_source(self) -> str:
        # Classic min-degree greedy baseline for MIS (priority = -degree).
        return (
            "def priority(v, graph):\n"
            "    # Baseline: minimum-degree greedy (the standard MIS heuristic).\n"
            "    return -float(graph.degree(v))\n"
        )


PROBLEMS: Dict[str, Callable[[], Problem]] = {
    "maxcut": MaxCut,
    "mis": MIS,
}


def get_problem(name: str) -> Problem:
    return PROBLEMS[name]()


# ---------------------------------------------------------------------------
# Graph generators (seeded, class-conditioned)
# ---------------------------------------------------------------------------


def _gen_graph(
    cls: str, n: int, rng: random.Random, *, weighted: bool
) -> List[Tuple[int, int, float]]:
    """Generate a graph of the requested class. Deterministic given ``rng``.

    * ``sparse``    — Erdős–Rényi with low edge probability (~avg degree 3).
    * ``dense``     — Erdős–Rényi with high edge probability (~0.5).
    * ``clustered`` — planted-partition / stochastic-block: dense inside blocks,
      sparse across — the regime where class-specialized heuristics pay off.
    """

    def w() -> float:
        return float(rng.randint(1, 10)) if weighted else 1.0

    edges: List[Tuple[int, int, float]] = []
    if cls == "sparse":
        p = min(1.0, 3.0 / max(1, n - 1))
        for u in range(n):
            for v in range(u + 1, n):
                if rng.random() < p:
                    edges.append((u, v, w()))
    elif cls == "dense":
        p = 0.5
        for u in range(n):
            for v in range(u + 1, n):
                if rng.random() < p:
                    edges.append((u, v, w()))
    elif cls == "clustered":
        k = max(2, n // 8)  # block size
        blocks = [list(range(i, min(i + k, n))) for i in range(0, n, k)]
        p_in, p_out = 0.7, 0.05
        for bi, block in enumerate(blocks):
            for i, u in enumerate(block):
                for v in block[i + 1 :]:
                    if rng.random() < p_in:
                        edges.append((u, v, w()))
            for other in blocks[bi + 1 :]:
                for u in block:
                    for v in other:
                        if rng.random() < p_out:
                            edges.append((u, v, w()))
    else:
        raise ValueError(f"unknown instance class: {cls}")
    return edges
